# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'realmSimple' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for realmSimple

  target 'realmSimple-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'realmSimpleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'realmSimple-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for realmSimple-tvOS

  target 'realmSimple-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
